#include <check.h>
Suite *LocalFileListSuite(void);
Suite *AmazonCredentialsSuite(void);
Suite *AmzHeadersSuite(void);
Suite *FileListStorageSuite(void);
Suite *RemoteListOfFilesSuite(void);
Suite *UploadSuite(void);
Suite *UtilsSuite(void);
Suite *DestinationSuite(void);
Suite *MicroCurlSuite(void);
